#!/usr/bin/env bash

set -e

if [[ -f /.dockerenv ]] || [[ -n "${REMOTE_CONTAINERS:-}" ]]; then
  cd "$(dirname "$0")/.."

  if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
  fi

  export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"
  exec hass --config "${PWD}/config" --debug
fi

exec "$(dirname "$0")/docker" develop "$@"
