#!/usr/bin/env bash

set -e

if [[ -f /.dockerenv ]] || [[ -n "${REMOTE_CONTAINERS:-}" ]]; then
  cd "$(dirname "$0")/.."
  python3 -m pip install --requirement requirements.txt
  python3 -m pip install --requirement requirements_test.txt
  exit 0
fi

exec "$(dirname "$0")/docker" setup "$@"
